services:
  backend:
    build: ./backend
    container_name: wishlist-backend
    ports:
      - "8020:8000"
    environment:
      - DATABASE_URL=sqlite:///./wishlist.db
    volumes:
      - ./backend/src:/app/src
      - ./backend/main.py:/app/main.py
      - ./backend/wishlist.db:/app/wishlist.db
    networks:
      - wishlist-network

  frontend:
    build: ./frontend
    container_name: wishlist-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - wishlist-network

networks:
  wishlist-network:
    driver: bridge
